# Create a read-only cross-account IAM role in CloudFormation, using the AWS-Managed Policy "ReadOnlyAccess":
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for enterprise IAM read-only role to deploy in each account, to be able to be assumed from the Management Account

Parameters:
# Create a parameter for the Management Account ID:
  ManagementAccountId:
    Type: String
    Description: Management Account ID
    MinLength: 12
    MaxLength: 12
    AllowedPattern: '^[0-9]+$'
    ConstraintDescription: Must be a 12-digit number.
# Create a parameter for the IAM role name:
  ReadOnlyRoleName:
    Type: String
    Description: IAM role name
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters and underscores.

Resources:
# Create the IAM role:
  ReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ReadOnlyRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${ManagementAccountId}:root'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess